<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5l5TSfsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5l5TSfs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5l5TSfs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'spot' => ['privates', '.errored..service_locator.5l5TSfs.App\\Entity\\Spot', NULL, 'Cannot autowire service ".service_locator.5l5TSfs": it needs an instance of "App\\Entity\\Spot" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'spot' => 'App\\Entity\\Spot',
        ]);
    }
}
