<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4npRb0DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4npRb0D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4npRb0D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'video' => ['privates', '.errored..service_locator.4npRb0D.App\\Entity\\Video', NULL, 'Cannot autowire service ".service_locator.4npRb0D": it needs an instance of "App\\Entity\\Video" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'video' => 'App\\Entity\\Video',
        ]);
    }
}
