<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F0YeAMqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F0YeAMq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F0YeAMq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'spot' => ['privates', '.errored..service_locator.F0YeAMq.App\\Entity\\Spot', NULL, 'Cannot autowire service ".service_locator.F0YeAMq": it needs an instance of "App\\Entity\\Spot" but this type has been excluded in "config/services.yaml".'],
        ], [
            'spot' => 'App\\Entity\\Spot',
        ]);
    }
}
