<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LS97MSmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lS97MSm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lS97MSm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playlistCategory' => ['privates', '.errored..service_locator.lS97MSm.App\\Entity\\PlaylistCategory', NULL, 'Cannot autowire service ".service_locator.lS97MSm": it needs an instance of "App\\Entity\\PlaylistCategory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'playlistCategory' => 'App\\Entity\\PlaylistCategory',
        ]);
    }
}
