<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DaYRdqOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.daYRdqO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.daYRdqO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'info' => ['privates', '.errored..service_locator.daYRdqO.App\\Entity\\Info', NULL, 'Cannot autowire service ".service_locator.daYRdqO": it needs an instance of "App\\Entity\\Info" but this type has been excluded in "config/services.yaml".'],
        ], [
            'info' => 'App\\Entity\\Info',
        ]);
    }
}
