<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PSaQCL_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pSaQCL.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pSaQCL.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'spotRepository' => ['privates', 'App\\Repository\\SpotRepository', 'getSpotRepositoryService', true],
        ], [
            'spotRepository' => 'App\\Repository\\SpotRepository',
        ]);
    }
}
