<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaylistCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QRu_ihG.App\Entity\PlaylistCategory' shared service.
     *
     * @return \App\Entity\PlaylistCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QRu_ihG": it needs an instance of "App\\Entity\\PlaylistCategory" but this type has been excluded in "config/services.yaml".');
    }
}
