<?php

namespace ContainerI34R33Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpot2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F0YeAMq.App\Entity\Spot' shared service.
     *
     * @return \App\Entity\Spot
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F0YeAMq": it needs an instance of "App\\Entity\\Spot" but this type has been excluded in "config/services.yaml".');
    }
}
