<?php

namespace ContainerDYXg2xh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I1Pp1jpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I1Pp1jp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I1Pp1jp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'infoCategoryRepository' => ['privates', 'App\\Repository\\InfoCategoryRepository', 'getInfoCategoryRepositoryService', true],
        ], [
            'infoCategoryRepository' => 'App\\Repository\\InfoCategoryRepository',
        ]);
    }
}
