<?php

namespace ContainerDYXg2xh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FE1FuQoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fE1FuQo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fE1FuQo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'playlistRepository' => ['privates', 'App\\Repository\\PlaylistRepository', 'getPlaylistRepositoryService', true],
        ], [
            'playlistRepository' => 'App\\Repository\\PlaylistRepository',
        ]);
    }
}
