<?php

namespace ContainerDYXg2xh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfoCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hIwBYyE.App\Entity\InfoCategory' shared service.
     *
     * @return \App\Entity\InfoCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hIwBYyE": it needs an instance of "App\\Entity\\InfoCategory" but this type has been excluded in "config/services.yaml".');
    }
}
